version: '3'
services:
  checkers:
    build: .
    container_name: checkers
    restart: always
    ports:
    - "12345:12345"
  # maybe we can also add volume to store history file in localdisk...